// File generated by FlutterFire CLI & Antigravity.
// Updated to support dev/prod flavors via --dart-define=FLAVOR=prod
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kDebugMode, kReleaseMode;


/// Build-time flavor constant.
/// Pass --dart-define=FLAVOR=prod when building the production flavor.
const String? _definedFlavor = bool.hasEnvironment('FLAVOR')
    ? String.fromEnvironment('FLAVOR')
    : null;

/// P0-15 (R-MOB-07): Fail-Closed Ortam Sözleşmesi
/// Release derlemelerinde FLAVOR tanımlanmamışsa derleme/başlatma sessizce dev'e düşmek yerine durdurulur.
String get resolvedFlavor {
  if (_definedFlavor != null && _definedFlavor!.isNotEmpty) {
    return _definedFlavor!;
  }
  if (kReleaseMode) {
    throw StateError(
      'KRİTİK HATA: Release derlemelerinde --dart-define=FLAVOR=(dev|prod) argümanı zorunludur! '
      'Ortam seçimi fail-closed olarak durduruldu.',
    );
  }
  return 'dev';
}

/// Returns true when building the production flavor.
bool get isProductionFlavor => resolvedFlavor == 'prod';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example (dev):
///   flutter run  --flavor dev  --dart-define=FLAVOR=dev
/// Example (prod):
///   flutter build appbundle --flavor prod --dart-define=FLAVOR=prod
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isProductionFlavor => resolvedFlavor == 'prod';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web her zaman DEV admin panelini gösterir; değiştirmeyin.
      return web;
    }
    final flavor = resolvedFlavor;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return flavor == 'prod' ? androidProd : androidDev;
      case TargetPlatform.iOS:
        return flavor == 'prod' ? iosProd : iosDev;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB (Admin paneli — her zaman DEV) ───────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmrSDBA_tzCCrPdDk28uMSXwpkDw_EZU',
    appId: '1:560592268193:web:64b68da3637d1e10d6f9e0',
    messagingSenderId: '560592268193',
    projectId: 'sicak-firsatlar-e6eae',
    authDomain: 'sicak-firsatlar-e6eae.firebaseapp.com',
    storageBucket: 'sicak-firsatlar-e6eae.firebasestorage.app',
  );

  // ─── ANDROID — DEV projesi (sicak-firsatlar-e6eae) ───────────────────────
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDOmrSDBA_tzCCrPdDk28uMSXwpkDw_EZU',
    appId: '1:560592268193:android:282d3a1048e2dec2d6f9e0',
    messagingSenderId: '560592268193',
    projectId: 'sicak-firsatlar-e6eae',
    storageBucket: 'sicak-firsatlar-e6eae.firebasestorage.app',
  );

  // ─── ANDROID — PROD projesi (firsatkolik-prod-e6eae) ─────────────────────
  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyC3lE2ktKnMO21KP1EMh2S173wjrSauiio',
    appId: '1:228657473310:android:f735a18f5c730ced380b0f',
    messagingSenderId: '228657473310',
    projectId: 'firsatkolik-prod-e6eae',
    storageBucket: 'firsatkolik-prod-e6eae.firebasestorage.app',
  );

  // ─── IOS — DEV projesi (sicak-firsatlar-e6eae) ─────────────────────────
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyCIX07mBffeH8PBHnzxDAqLo6saSffQ2CM',
    appId: '1:560592268193:ios:be496ea2d9e55177d6f9e0',
    messagingSenderId: '560592268193',
    projectId: 'sicak-firsatlar-e6eae',
    storageBucket: 'sicak-firsatlar-e6eae.firebasestorage.app',
    iosBundleId: 'com.firsatkolik.app',
    iosClientId: '560592268193-a70ituj4997v31non78gvno3f5tsked7.apps.googleusercontent.com',
  );

  // ─── IOS — PROD projesi (firsatkolik-prod-e6eae) ───────────────────────
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyDs2l88K4w-4GaMPrYcCfDbp5VX9EXoyBE',
    appId: '1:228657473310:ios:5f779f3647ed4dd2380b0f',
    messagingSenderId: '228657473310',
    projectId: 'firsatkolik-prod-e6eae',
    storageBucket: 'firsatkolik-prod-e6eae.firebasestorage.app',
    iosBundleId: 'com.firsatkolik.app',
    iosClientId: '228657473310-7dlhjuj25p2ov8o5274n3o3759h6gubs.apps.googleusercontent.com',
  );

  // ─── Kısayol: mevcut flavor'ın project ID'si ─────────────────────────────
  /// Cloud Function URL'leri gibi proje kimliğini gerektiren yerlerde kullanın.
  /// Örnek: 'https://us-central1-${DefaultFirebaseOptions.flavorProjectId}.cloudfunctions.net/...'
  static String get flavorProjectId =>
      isProductionFlavor ? 'firsatkolik-prod-e6eae' : 'sicak-firsatlar-e6eae';

  // ─── AdMob Reklam Birimi Kimlikleri (4 Boyutlu Matris: Dev/Prod x Android/iOS) ───

  /// iOS Prod Banner ID (Eski/Geçişli Banner Birimi - Faz 3.3 ile Native Ads'e geçildi)
  static const String _iosProdBannerId = String.fromEnvironment(
    'ADMOB_IOS_BANNER_ID',
    defaultValue: 'ca-app-pub-6853997017739651/2039078155', // FırsatKolik Gerçek iOS Banner ID
  );

  /// Android Prod Banner ID (Eski/Geçişli Banner Birimi - Faz 3.3 ile Native Ads'e geçildi)
  static const String _androidProdBannerId = 'ca-app-pub-6853997017739651/8758625050';

  /// Banner Reklam Birimi ID'si (DEPRECATED: Faz 3.3 kapsamında akış içi reklamlar nativeAdUnitId'ye taşınmıştır)
  @Deprecated('Faz 3.3 kapsamında akış içi reklamlar nativeAdUnitId formatına taşınmıştır.')
  static String get bannerAdUnitId {
    final isDev = kDebugMode || !isProductionFlavor;
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      if (isDev || _iosProdBannerId.isEmpty) {
        return 'ca-app-pub-3940256099942544/2934735716'; // Google iOS Test Banner ID
      }
      return _iosProdBannerId;
    }
    return isDev
        ? 'ca-app-pub-3940256099942544/6300978111' // Google Android Test Banner ID
        : _androidProdBannerId; // Gerçek Android Banner ID
  }



  /// iOS Prod Native Ad ID (FırsatKolik iOS Prod Yerel Akış Reklam Birimi)
  static const String _iosProdNativeId = String.fromEnvironment(
    'ADMOB_IOS_NATIVE_ID',
    defaultValue: 'ca-app-pub-6853997017739651/9437070495', // FırsatKolik Prod iOS Native ID
  );

  /// Android Prod Native Ad ID (FırsatKolik Android Prod Yerel Akış Reklam Birimi)
  static const String _androidProdNativeId = String.fromEnvironment(
    'ADMOB_ANDROID_NATIVE_ID',
    defaultValue: 'ca-app-pub-6853997017739651/4004866134', // FırsatKolik Prod Android Native ID
  );

  /// Yerel Reklam (Native Advanced) Birimi ID'si (Akış İçi Grid & List Birimleri)
  static String get nativeAdUnitId {
    final isDev = kDebugMode || !isProductionFlavor;
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      if (isDev || _iosProdNativeId.isEmpty) {
        return 'ca-app-pub-3940256099942544/3986624511'; // Google iOS Test Native ID
      }
      return _iosProdNativeId;
    }
    return isDev
        ? 'ca-app-pub-3940256099942544/2247696110' // Google Android Test Native ID
        : _androidProdNativeId; // FırsatKolik Gerçek Android Native ID
  }

  /// Ödüllü Reklam (Rewarded) Birimi ID'si
  static String get rewardedAdUnitId {
    final isDev = kDebugMode || !isProductionFlavor;
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      const iosProdId = String.fromEnvironment('ADMOB_REWARDED_IOS');
      if (iosProdId.isNotEmpty && !isDev) return iosProdId;
      return 'ca-app-pub-3940256099942544/1712485313'; // Google iOS Test Rewarded ID
    }
    const androidProdId = String.fromEnvironment('ADMOB_REWARDED_ANDROID', defaultValue: 'ca-app-pub-6853997017739651/5224354917');
    return isDev
        ? 'ca-app-pub-3940256099942544/5224354917' // Google Android Test Rewarded ID
        : androidProdId;
  }

}


